### ISSUE TITLE
The extension doesn't include media in searches

### ISSUE THREAD

**Issue by BrElio** [searchwp/searchwp-privatecontent#1]
The query used by the extension at line 125 of searchwp-privatecontent.php would not include media as there is no "post_status" specified in the args and therefore defaults to publish.
But media have a post status of "inherit".

**Comment by jchristopher** [comment]
Fixed in https://github.com/searchwp/searchwp-privatecontent/commit/5d637817b24a98450a3767f14954ac04c04724b7
